### ISSUE TITLE
Compilation on R 4.0.x fails

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [nx10/unigd#33]
### Describe the bug

Starting with version 1.0.3, unigd does not compile on R 4.0.x.

<details>
<summary> Compiler error</summary>
<pre>
In file included from page_store.cpp:2:
page_store.h:63:8: error: ‘shared_timed_mutex’ in namespace ‘std’ does not name a type
   63 |   std::shared_timed_mutex m_store_mutex;
      |        ^~~~~~~~~~~~~~~~~~
page_store.h:63:3: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
   63 |   std::shared_timed_mutex m_store_mutex;
      |   ^~~
page_store.cpp: In member function ‘std::experimental::optional<int> unigd::page_store::normalize_index(unigd::ex::plot_relative_t)’:
page_store.cpp:26:14: error: ‘shared_lock’ in namespace ‘std’ does not name a template type
   26 |   const std::shared_lock<std::shared_timed_mutex> r_lock(m_store_mutex);
      |              ^~~~~~~~~~~
page_store.cpp:26:9: note: ‘std::shared_lock’ is only available from C++14 onwards
   26 |   const std::shared_lock<std::shared_timed_mutex> r_lock(m_store_mutex);
      |         ^~~
page_store.cpp: In member function ‘unigd::ex::plot_index_t unigd::page_store::append(unigd::gvertex<double>)’:
page_store.cpp:36:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
   36 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                               ^~~~~~~~~~~~~~~~~~
page_store.cpp:36:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:36:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
page_store.cpp:36:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:36:49: error: template argument 1 is invalid
   36 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                 ^
page_store.cpp:36:58: error: ‘m_store_mutex’ was not declared in this scope
   36 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                          ^~~~~~~~~~~~~
page_store.cpp: In member function ‘void unigd::page_store::add_dc(unigd::ex::plot_relative_t, std::unique_ptr<unigd::renderers::DrawCall>&&, bool)’:
page_store.cpp:46:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
   46 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                               ^~~~~~~~~~~~~~~~~~
page_store.cpp:46:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:46:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
page_store.cpp:46:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:46:49: error: template argument 1 is invalid
   46 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                 ^
page_store.cpp:46:58: error: ‘m_store_mutex’ was not declared in this scope
   46 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                          ^~~~~~~~~~~~~
page_store.cpp: In member function ‘void unigd::page_store::add_dc(unigd::ex::plot_relative_t, std::vector<std::unique_ptr<unigd::renderers::DrawCall> >&&, bool)’:
page_store.cpp:63:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
   63 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                               ^~~~~~~~~~~~~~~~~~
page_store.cpp:63:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:63:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
page_store.cpp:63:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:63:49: error: template argument 1 is invalid
   63 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                 ^
page_store.cpp:63:58: error: ‘m_store_mutex’ was not declared in this scope
   63 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                          ^~~~~~~~~~~~~
page_store.cpp: In member function ‘void unigd::page_store::clear(unigd::ex::plot_relative_t, bool)’:
page_store.cpp:78:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
   78 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                               ^~~~~~~~~~~~~~~~~~
page_store.cpp:78:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:78:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
page_store.cpp:78:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:78:49: error: template argument 1 is invalid
   78 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                 ^
page_store.cpp:78:58: error: ‘m_store_mutex’ was not declared in this scope
   78 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                          ^~~~~~~~~~~~~
page_store.cpp: In member function ‘bool unigd::page_store::remove(unigd::ex::plot_relative_t, bool)’:
page_store.cpp:92:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
   92 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                               ^~~~~~~~~~~~~~~~~~
page_store.cpp:92:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:92:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
page_store.cpp:92:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:92:49: error: template argument 1 is invalid
   92 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                 ^
page_store.cpp:92:58: error: ‘m_store_mutex’ was not declared in this scope
   92 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                          ^~~~~~~~~~~~~
page_store.cpp: In member function ‘bool unigd::page_store::remove_all()’:
page_store.cpp:109:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
  109 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                               ^~~~~~~~~~~~~~~~~~
page_store.cpp:109:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:109:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
page_store.cpp:109:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:109:49: error: template argument 1 is invalid
  109 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                 ^
page_store.cpp:109:58: error: ‘m_store_mutex’ was not declared in this scope
  109 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                          ^~~~~~~~~~~~~
page_store.cpp: In member function ‘void unigd::page_store::fill(unigd::ex::plot_relative_t, unigd::color_t)’:
page_store.cpp:125:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
  125 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                               ^~~~~~~~~~~~~~~~~~
page_store.cpp:125:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:125:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
page_store.cpp:125:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:125:49: error: template argument 1 is invalid
  125 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                 ^
page_store.cpp:125:58: error: ‘m_store_mutex’ was not declared in this scope
  125 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                          ^~~~~~~~~~~~~
page_store.cpp: In member function ‘void unigd::page_store::resize(unigd::ex::plot_relative_t, unigd::gvertex<double>)’:
page_store.cpp:135:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
  135 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                               ^~~~~~~~~~~~~~~~~~
page_store.cpp:135:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:135:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
page_store.cpp:135:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:135:49: error: template argument 1 is invalid
  135 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                 ^
page_store.cpp:135:58: error: ‘m_store_mutex’ was not declared in this scope
  135 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                          ^~~~~~~~~~~~~
page_store.cpp: In member function ‘unigd::gvertex<double> unigd::page_store::size(unigd::ex::plot_relative_t)’:
page_store.cpp:146:14: error: ‘shared_lock’ in namespace ‘std’ does not name a template type
  146 |   const std::shared_lock<std::shared_timed_mutex> r_lock(m_store_mutex);
      |              ^~~~~~~~~~~
page_store.cpp:146:9: note: ‘std::shared_lock’ is only available from C++14 onwards
  146 |   const std::shared_lock<std::shared_timed_mutex> r_lock(m_store_mutex);
      |         ^~~
page_store.cpp: In member function ‘void unigd::page_store::clip(unigd::ex::plot_relative_t, unigd::grect<double>)’:
page_store.cpp:156:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
  156 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                               ^~~~~~~~~~~~~~~~~~
page_store.cpp:156:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:156:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
page_store.cpp:156:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:156:49: error: template argument 1 is invalid
  156 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                 ^
page_store.cpp:156:58: error: ‘m_store_mutex’ was not declared in this scope
  156 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                          ^~~~~~~~~~~~~
page_store.cpp: In member function ‘bool unigd::page_store::render(unigd::ex::plot_relative_t, unigd::renderers::render_target*, double)’:
page_store.cpp:168:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
  168 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                               ^~~~~~~~~~~~~~~~~~
page_store.cpp:168:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:168:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
page_store.cpp:168:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:168:49: error: template argument 1 is invalid
  168 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                 ^
page_store.cpp:168:58: error: ‘m_store_mutex’ was not declared in this scope
  168 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                          ^~~~~~~~~~~~~
page_store.cpp: In member function ‘bool unigd::page_store::render_if_size(unigd::ex::plot_relative_t, unigd::renderers::render_target*, double, unigd::gvertex<double>)’:
page_store.cpp:182:14: error: ‘shared_lock’ in namespace ‘std’ does not name a template type
  182 |   const std::shared_lock<std::shared_timed_mutex> r_lock(m_store_mutex);
      |              ^~~~~~~~~~~
page_store.cpp:182:9: note: ‘std::shared_lock’ is only available from C++14 onwards
  182 |   const std::shared_lock<std::shared_timed_mutex> r_lock(m_store_mutex);
      |         ^~~
page_store.cpp: In member function ‘std::experimental::optional<unsigned int> unigd::page_store::find_index(unigd::ex::plot_id_t)’:
page_store.cpp:214:14: error: ‘shared_lock’ in namespace ‘std’ does not name a template type
  214 |   const std::shared_lock<std::shared_timed_mutex> r_lock(m_store_mutex);
      |              ^~~~~~~~~~~
page_store.cpp:214:9: note: ‘std::shared_lock’ is only available from C++14 onwards
  214 |   const std::shared_lock<std::shared_timed_mutex> r_lock(m_store_mutex);
      |         ^~~
page_store.cpp: In member function ‘unigd_device_state unigd::page_store::state()’:
page_store.cpp:228:14: error: ‘shared_lock’ in namespace ‘std’ does not name a template type
  228 |   const std::shared_lock<std::shared_timed_mutex> r_lock(m_store_mutex);
      |              ^~~~~~~~~~~
page_store.cpp:228:9: note: ‘std::shared_lock’ is only available from C++14 onwards
  228 |   const std::shared_lock<std::shared_timed_mutex> r_lock(m_store_mutex);
      |         ^~~
page_store.cpp: In member function ‘void unigd::page_store::set_device_active(bool)’:
page_store.cpp:234:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
  234 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                               ^~~~~~~~~~~~~~~~~~
page_store.cpp:234:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:234:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
page_store.cpp:234:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:234:49: error: template argument 1 is invalid
  234 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                 ^
page_store.cpp:234:58: error: ‘m_store_mutex’ was not declared in this scope
  234 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                          ^~~~~~~~~~~~~
page_store.cpp: In member function ‘unigd::ex::find_results unigd::page_store::query(unigd::ex::plot_relative_t, unigd::ex::plot_id_t)’:
page_store.cpp:240:14: error: ‘shared_lock’ in namespace ‘std’ does not name a template type
  240 |   const std::shared_lock<std::shared_timed_mutex> r_lock(m_store_mutex);
      |              ^~~~~~~~~~~
page_store.cpp:240:9: note: ‘std::shared_lock’ is only available from C++14 onwards
  240 |   const std::shared_lock<std::shared_timed_mutex> r_lock(m_store_mutex);
      |         ^~~
page_store.cpp: In member function ‘void unigd::page_store::extra_css(std::experimental::optional<std::__cxx11::basic_string<char> >)’:
page_store.cpp:263:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
  263 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                               ^~~~~~~~~~~~~~~~~~
page_store.cpp:263:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:263:31: error: ‘shared_timed_mutex’ is not a member of ‘std’
page_store.cpp:263:31: note: ‘std::shared_timed_mutex’ is only available from C++14 onwards
page_store.cpp:263:49: error: template argument 1 is invalid
  263 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                 ^
page_store.cpp:263:58: error: ‘m_store_mutex’ was not declared in this scope
  263 |   const std::unique_lock<std::shared_timed_mutex> w_lock(m_store_mutex);
      |                                                          ^~~~~~~~~~~~~
make: *** [/opt/R/4.0.5/lib/R/etc/Makeconf:181: page_store.o] Error 1
</pre>
</details>

### To Reproduce

On R 4.0.5, run
```r
devtools::install_github("nx10/unigd","v0.1.3")
```

### Expected behavior

Like in
```r
devtools::install_github("nx10/unigd","v0.1.2")
```

### Environment
 - OS: Ubuntu Linux 22.04
 - R version: 4.0.5
 - unigd version: 0.1.3

### Work-arounds
- upgrade R
- revert to 0.1.2
- play with CXXFLAGS: `withr::with_makevars(c(CXXFLAGS="-std=c++14"), {devtools::install_github("nx10/unigd","v0.1.3", force = TRUE)})`

**Comment by nx10** [comment]
Do you still need 4.0 support? I've modernized the build system but also bumped up minimum supported version to 4.2 (almost 4 years old at this point) as testing across so many releases, compilers and OSs became unfeasible.

**Comment by HenningLorenzen-ext-bayer** [comment]
> Do you still need 4.0 support? I've modernized the build system but also bumped up minimum supported version to 4.2 (almost 4 years old at this point) as testing across so many releases, compilers and OSs became unfeasible.

You make a fair point. Go ahead with your plan and many thanks for your continued work!
